### ISSUE TITLE
"file not found" on clean install when running gulp

### ISSUE THREAD

**Issue by ceelian** [dsebastien/modernWebDevGenerator#69] opened 2016-01-21 17:46 UTC
When running gulp on a fresh project I got this error:

```
[...]
[18:38:06] Starting 'images'...
[18:38:06] 'scripts-javascript-dist' errored after 1.23 s
[18:38:06] Error on fetch for .tmp/core/boot.js at file:///Users/ceelian/tmp/modernwebdevgenerator/.tmp/core/boot.js
    Error: ENOENT: no such file or directory, open '/Users/ceelian/tmp/modernwebdevgenerator/.tmp/core/boot.js'
    at Error (native)

[18:38:06] 'default' errored after 1.26 s
[18:38:06] Error in plugin 'run-sequence'
Message:
    An error occured in task 'scripts-javascript-dist'.
[18:38:07] styles-vendor-dist all files 1.87 kB
[18:38:07] Finished 'styles-vendor-dist' after 2.08 s
[...]
```

System is OS X.

**Comment by dsebastien** [comment] 2016-01-21 17:55
Hi,

This is a duplicate of #66.
I'll do the follow-up here: https://github.com/dsebastien/modernWebDevBuild/issues/89

**Closed as completed** 2016-01-22 01:28 UTC
Labels: duplicate
